#If compiled with fujitsu f90
#include fujitsu.def

#If compiled with pgf90
#include pgf90.def

##If compiled with ifort
#include ifort.def

#If compiled with gfortran
	include gfortran.def

#If compiled with gfortran-10
#include gfortran-10.def

# Include HPRMAT configuration (generated by setup.sh)
-include hprmat.inc


# If compiled with gfortran
#FC=gfortran
#FFLAGS= -O2 -Wtabs  -ffixed-form # -fbounds-check
#FFLAGS1= -O2 -Wtabs  -ffixed-form # -fbounds-check

LBITS := $(shell getconf LONG_BIT)
ifeq ($(LBITS),64)
# Compile with 64-bits lapack
#LFLAGS= -L./lapack64 -llapack -lrefblas
else
# Compile with 32-bits lapack
#LFLAGS= -L./lapack -llapack -lrefblas
endif



# BINDIR= directory to install executables
BINDIR=$(PWD)/bin
TOPDIR=$(PWD)
SRC=$(TOPDIR)

.SUFFIXES: .c .o

OBJ=modules.o coul90.o precision.o gpu_solver_interface.o rmat_solvers.o rmatrix_hp.o scatcc.o  channels.o writecdccwf.o  basis.o hdiag.o ho.o lst-amos.o utils.o cgbasis.o \
    pauli.o sort.o nag2.o whittaker.o  \
     continuum.o belam.o bmlam.o ham.o  transition_targdef.o\
        transition.o   clebsg.o  projpot.o fragpot.o xsections_alpha_1d.o \
        rmatel.o solvecc.o rmatrix.o ccbins.o xsections.o xsections_alpha.o rsc.o\
	bincc2.o ceigen.o readwf.o  thox.o eigcc.o

# Add CUDA object if GPU enabled, otherwise use stub
ifeq ($(GPU_ENABLED),true)
OBJ += cusolver_interface.o
else
OBJ += cusolver_stub.o
endif

#coulfg4.f
all: $(OBJ)
	$(FC) -o thox $(OBJ) $(LFLAGS) $(LIBS) $(PARALLEL)  
#	$(FC) -g -o thox $(OBJ) $(LFLAGS) -L./lapack64 -llapack -lrefblas
#	$(FC) -g -o thox $(OBJ) $(LFLAGS) -L./lapack -llapack -lrefblas
modules.o:modules.f90
	$(FC) $(FFLAGS) -c modules.f90
# C compiler for stub
CC = gcc

# HPRMAT files use free-form Fortran
FFLAGS_FREE = -O3 -fopenmp -ffree-form
precision.o:precision.F90
	$(FC) $(FFLAGS_FREE) -c precision.F90
gpu_solver_interface.o:gpu_solver_interface.F90 precision.o
	$(FC) $(FFLAGS_FREE) -c gpu_solver_interface.F90
# CUDA compilation rule (only if GPU enabled), otherwise use stub
ifeq ($(GPU_ENABLED),true)
cusolver_interface.o:cusolver_interface.cu
	$(NVCC) $(NVCCFLAGS) -arch=$(GPU_ARCH) -c cusolver_interface.cu
else
cusolver_stub.o:cusolver_stub.c
	$(CC) -c cusolver_stub.c
endif
rmat_solvers.o:rmat_solvers.F90 precision.o gpu_solver_interface.o
	$(FC) $(FFLAGS_FREE) -c rmat_solvers.F90
rmatrix_hp.o:rmatrix_hp.F90 rmat_solvers.o
	$(FC) $(FFLAGS_FREE) -c rmatrix_hp.F90
thox.o:thox.f90 modules.f90
	$(FC) $(FFLAGS) -c thox.f90
ho.o:ho.f90 modules.f90
	$(FC) $(FFLAGS) -c ho.f90
cgbasis.o:cgbasis.f90 modules.f90
	$(FC) $(FFLAGS) -c cgbasis.f90	
lst-amos.o:lst-amos.f90 modules.f90
	$(FC) $(FFLAGS) -c lst-amos.f90
basis.o:basis.f90 modules.f90
	$(FC) $(FFLAGS) -c basis.f90
ham.o:ham.f90 modules.f90
	$(FC) $(FFLAGS) -c ham.f90
hdiag.o:hdiag.f90 modules.f90
	$(FC) $(FFLAGS) -c hdiag.f90
utils.o:utils.f90 modules.f90
	$(FC) $(FFLAGS) -c utils.f90
pauli.o:pauli.f90 modules.f90
	$(FC) $(FFLAGS) -c pauli.f90
sort.o:sort.f90 modules.f90
	$(FC) $(FFLAGS) -c sort.f90
nag2.o:nag2.f90 modules.f90
	$(FC) $(FFLAGS) -c nag2.f90
whittaker.o:whittaker.f90 modules.f90
	$(FC) $(FFLAGS) -c whittaker.f90
coul90.o:coul90.f modules.f90
	$(FC) $(FFLAGS1) -c coul90.f
ccbins.o:ccbins.f90 modules.f90
	$(FC) $(FFLAGS1) -c ccbins.f90
continuum.o:continuum.f90 modules.f90
	$(FC) $(FFLAGS1) -c continuum.f90
scatcc.o:scatcc.f90 modules.f90 rmatrix_hp.o
	$(FC) $(FFLAGS1) -c scatcc.f90 
coulfg4.o:coulfg4.f modules.f90
	$(FC) $(FFLAGS1) -c coulfg4.f
belam.o:belam.f90 modules.f90
	$(FC) $(FFLAGS1) -c belam.f90
bmlam.o:bmlam.f90 modules.f90
	$(FC) $(FFLAGS1) -c bmlam.f90	
transition.o:transition.f90 modules.f90
	$(FC) $(FFLAGS1)  -c transition.f90
transition_targdef.o:transition_targdef.f90 modules.f90
	$(FC) $(FFLAGS1)  -c transition_targdef.f90
fragpot.o:fragpot.f90 modules.f90
	$(FC) $(FFLAGS1) -c fragpot.f90
projpot.o:projpot.f90 modules.f90
	$(FC) $(FFLAGS1) -c projpot.f90
rmatel.o:rmatel.f90 modules.f90
	$(FC) $(FFLAGS1) -c rmatel.f90
read_frad.o:read_frad.f90 modules.f90
	$(FC) $(FFLAGS1) -c read_frad.f90
clebsg.o:clebsg.f90 modules.f90
	$(FC) $(FFLAGS1) -c clebsg.f90
solvecc.o:solvecc.f90 modules.f90 rmatrix_hp.o
	$(FC) $(FFLAGS) -c solvecc.f90
xsections.o:xsections.f90
	$(FC) $(FFLAGS) $(PARALLEL) -c  xsections.f90
xsections_alpha.o:xsections_alpha.f90
	$(FC) $(FFLAGS) $(PARALLEL) -c  xsections_alpha.f90
xsections_alpha_1d.o:xsections_alpha_1d.f90
	$(FC) $(FFLAGS) $(PARALLEL) -c  xsections_alpha_1d.f90
lapack.o:lapack.f 
	$(FC) $(FFLAGS) -c lapack.f
dsyev-lapack.o:dsyev-lapack.f 
	$(FC) $(FFLAGS) -c dsyev-lapack.f
rmatrix.o:rmatrix.f
	$(FC) $(FFLAGS) -c rmatrix.f
bincc2.o:bincc2.f
	$(FC) $(FFLAGS) -c bincc2.f
ceigen.o:ceigen.F
	$(FC) $(FFLAGS2) -c ceigen.F
readwf.o:readwf.f90
	$(FC) $(FFLAGS) -c readwf.f90
channels.o:channels.f
	$(FC) $(FFLAGS) -c channels.f
writecdccwf.o:writecdccwf.f
	$(FC) $(FFLAGS) -c writecdccwf.f
eigcc.o:eigcc.f modules.f90
	$(FC) $(FFLAGS1) -c eigcc.f
rsc.o:rsc.f90
	$(FC) $(FFLAGS) -c rsc.f90

install: all
#%if BINDIR
	-mkdir $(BINDIR)
	 @echo 
	 @echo Installing executables on $(BINDIR) 
	 @echo -------------------------------------------------
	-cp $(SRC)/thox $(BINDIR)/
	@echo ---------------------------------------------------

clean:
	rm -f *.o core
	rm -f *.mod
# DO NOT DELETE



